#!/bin/sh

#echo 'hello, Chunis! ^_^'

export HISTCONTROL=ignoredups
export HISTFILESIZE=8000
export PATH=$HOME/.rbenv/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH:~/bin

set -o noclobber
set +o ignoreeof
#shopt -s cdspell
shopt -s checkwinsize

name=`hostname`
PS1='\[\e]2;\u@\H \w\a\e[32;1m\][$name \W]\\$ \[\e[0m\]'

##eval `dircolors ~/.coloursrc`
#eval `dircolors ~/.coloursrc2`

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    alias dir='ls --color=auto --format=vertical'
    alias vdir='ls --color=auto --format=long'
fi


