#!/bin/sh


alias whs=whereis
alias was=whatis
alias ehco=echo
alias chx='chmod +x'
alias grep='grep --color -n'
alias grepr='grep --color -nr'
alias locate='locate -i'
alias vi=vim
alias iv=vi

alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

alias ls='ls --color '
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
#alias l=ls
alias s=ls
alias sl=ls

alias d=cd
alias scd=cd
alias c=cd
alias cd='cd '
alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'
alias ..='..'
alias ...='../..'
alias ....='../../..'
alias .....='../../../..'
alias ......='../../../../..'


# for git
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gr='git remote'
