#!/bin/sh

myconf=~/myconf/dot_files

[ -z "$PS1" ] && return

[ -f /etc/bashrc ] && . /etc/bashrc
[ -f /etc/bash_completion ] && . /etc/bash_completion

source $myconf/bash_myconf
source $myconf/bash_alias
source $myconf/myalias
source $myconf/bash_myfunc
